import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Nav from "./components/Nav";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // footer is hidden to hide sign up link
    <ClerkProvider appearance={{ elements: { footer: "hidden" } }}>
      <html lang="en">
        <body className={roboto.className}>
          <Nav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
